theme: jekyll-theme-minimal
title: Samuel Espley
description: |-
  Computational Chemistry<br>
  ----<br>
  Cheminformatics<br>
  ----<br>
  Machine Learning<br> 
  ----<br>
  Hi to whoever is reading this! As I am approaching the end of my PhD (September 2024) I thought it would be a good idea to consolidate what I have learnt and what thoughts I have had throughout. This will primarily be for little code snippets and how to's that I think may be useful to someone. Even if they aren't, writing it will be helpful to me!\nIn the event that this develops into me posting my opinions...
  ***all opinions and views are my own and are in no way representative of sponsors or employers***. 
