theme: jekyll-theme-minimal
title: Samuel Espley
description: |-
  <i>Computational Chemistry</i><br>
  ----<br>
  <i>Cheminformatics</i><br>
  ----<br>
  <i>Machine Learning</i><br> 
  ----<br>
  Hi to whoever is reading this! As I am approaching the end of my PhD (September 2024) I thought it would be a good idea to consolidate what I have learnt and what thoughts I have had throughout. This will primarily be for little code snippets and how to's that I think may be useful to someone. Even if they aren't, writing it will be helpful to me!<br>
  In the event that this develops into me posting my opinions... <b>all opinions and views are my own and are in no way representative of sponsors or employers</b>.<br> 
  <a href="https://samgeoesp.github.io/tl_paper.html">Transfer Learning for Reaction Barrier Predictions<a><br>
  
